# Generated by Django 3.0.6 on 2020-05-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_descprition', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
